In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')
%matplotlib inline

In [2]:
def cleanMoviesUped(movieString):
    movieStringnew = movieString.split('),')
    for c in range(len(movieStringnew)-1):
        movieStringnew[c] = movieStringnew[c]+')'
    return movieStringnew

In [16]:
qq = 'When Harry Met Sally... (1989),Much Ado About Nothing (1993),Some Like It Hot (1959),Finding Nemo (2003),Modern Times (1936),Manhattan (1979),Wallace &amp; Gromit: The Wrong Trousers (1993)'

In [17]:
qq2 = 'Scarface (1983),Pulp Fiction (1994),Monsters, Inc. (2001)'

In [20]:
qq2_clean = cleanMoviesUped(qq2)

In [10]:
new_df3 = pd.read_csv('df_Soup_18K.csv')
cosine_sim = pd.read_csv('cosine_sim_Soup_18K.csv')

In [14]:
def weighted_rating2(x):
    v = x['vote_count']
    R = x['vote_average']
    m=50
    C=2.5
    return (v/(v+m) * R) + (m/(m+v) * C)

def improved_recommendations(title):
    cosine_sim2 = cosine_sim.values 
    titles = new_df3['title_x']
    indices = pd.Series(new_df3.index, index=new_df3['title_x'])

    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim2[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:26]
    movie_indices = [i[0] for i in sim_scores]
    
    movies = new_df3.iloc[movie_indices][['title_x', 'vote_count', 'vote_average', 'year']]
    vote_counts = movies[movies['vote_count'].notnull()]['vote_count'].astype('int')
    vote_averages = movies[movies['vote_average'].notnull()]['vote_average'].astype('int')
    C = vote_averages.mean()
#     m = vote_counts.quantile(0.60)
    m = 50
#     print(C)
#     print(m)
    qualified = movies[(movies['vote_count'] >= m) & (movies['vote_count'].notnull()) & (movies['vote_average'].notnull())]
    qualified['vote_count'] = qualified['vote_count'].astype('int')
    qualified['vote_average'] = qualified['vote_average'].astype('int')
    qualified['wr'] = qualified.apply(weighted_rating2, axis=1)
#     print(qualified)
    qualified = qualified.sort_values('wr', ascending=False).head(10)
    return qualified['title_x']

In [15]:
improved_recommendations('Finding Nemo (2003)')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1667                              American Tail, An (1986)
2753                         Road to El Dorado, The (2000)
2483                      7th Voyage of Sinbad, The (1958)
3261                      Brave Little Toaster, The (1987)
5625                                 Beyond Borders (2003)
7318     Twelve Tasks of Asterix, The (Les douze travau...
16108                                      99 Homes (2014)
15983                       The Fox and the Hound 2 (2006)
2160                             Outrageous Fortune (1987)
4021                      Jimmy Neutron: Boy Genius (2001)
Name: title_x, dtype: object

In [21]:
improved_recommendations('Monsters, Inc. (2001)')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

2111                                         Tarzan (1999)
1903                                Civil Action, A (1998)
9536                            Monsters University (2013)
3955                                    Jabberwocky (1977)
3298                             Monster Squad, The (1987)
7318     Twelve Tasks of Asterix, The (Les douze travau...
17247                                Brother Bear 2 (2006)
13111                           Secret of the Wings (2012)
12970            Toy Story Toons: Hawaiian Vacation (2011)
12972                    Toy Story Toons: Small Fry (2011)
Name: title_x, dtype: object

In [50]:
qq2_clean

['Scarface (1983)', 'Pulp Fiction (1994)', 'Monsters, Inc. (2001)']

In [51]:
testing12 = 'Braveheart (1995),Toy Story (1995)'
testing12_clean = cleanMoviesUped(testing12)
testing12_clean

['Braveheart (1995)', 'Toy Story (1995)']

In [52]:
list_of_df = []
for k in testing12_clean:
    print(k)
    output = improved_recommendations(k)
    print('one done')
    list_of_df.append(output)
newoutput = pd.concat(list_of_df)

Braveheart (1995)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

one done
Toy Story (1995)
one done

In [53]:
newoutput

5806     Nausicaä of the Valley of the Wind (Kaze no ta...
3182     Crouching Tiger, Hidden Dragon (Wo hu cang lon...
2935                  Road Warrior, The (Mad Max 2) (1981)
2220                              13th Warrior, The (1999)
1241                            Conan the Barbarian (1982)
6472                     Chronicles of Riddick, The (2004)
4092                                  Birthday Girl (2001)
7143                                   Vikings, The (1958)
7774                                   Warrior, The (2001)
4179     He Knows You're Alone (a.k.a. Blood Wedding) (...
1667                              American Tail, An (1986)
17019                                          Home (2015)
7318     Twelve Tasks of Asterix, The (Les douze travau...
14174                    Toy Story That Time Forgot (2014)
2980                                         Asylum (1972)
17399                              Batman vs. Robin (2015)
17247                                Brother Bear 2 (2006)
13621                  Ice Age: A Mammoth Christmas (2011)
12970            Toy Story Toons: Hawaiian Vacation (2011)
12972                    Toy Story Toons: Small Fry (2011)
Name: title_x, dtype: object

In [42]:
nemo_rec = improved_recommendations('Finding Nemo (2003)')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [32]:
noNA = pd.read_csv('posters_18k_clean.csv')

In [35]:
noNA.head()

,movieId,wr,year,title2,genres,imdbId_y,poster_y,title,tmdbId_y
0,1,3.860736,1995,toystory,Adventure|Animation|Children|Comedy|Fantasy,114709,https://image.tmdb.org/t/p/w500/rhIRbceoE9lR4v...,Toy Story (1995),862.0
1,2,3.222923,1995,jumanji,Adventure|Children|Fantasy,113497,https://image.tmdb.org/t/p/w500/vgpXmVaVyUL7GG...,Jumanji (1995),8844.0
2,3,3.161005,1995,grumpieroldmen,Comedy|Romance,113228,https://image.tmdb.org/t/p/w500/6ksm1sjKMFLbO7...,Grumpier Old Men (1995),15602.0
3,4,2.955906,1995,waitingtoexhale,Comedy|Drama|Romance,114885,https://image.tmdb.org/t/p/w500/16XOMpEaLWkrcP...,Waiting to Exhale (1995),31357.0
4,5,3.077226,1995,fatherofthebridepartii,Comedy,113041,https://image.tmdb.org/t/p/w500/e64sOI48hQXyru...,Father of the Bride Part II (1995),11862.0

In [36]:
noNA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17367 entries, 0 to 17366
Data columns (total 9 columns):
movieId     17367 non-null int64
wr          17367 non-null float64
year        17367 non-null object
title2      17367 non-null object
genres      17367 non-null object
imdbId_y    17367 non-null int64
poster_y    17367 non-null object
title       17367 non-null object
tmdbId_y    17367 non-null float64
dtypes: float64(2), int64(2), object(5)
memory usage: 1.2+ MB

In [37]:
df_movies_POSTERS = pd.read_csv('posters_18k.csv')

In [39]:
df_movies_POSTERS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26721 entries, 0 to 26720
Data columns (total 9 columns):
movieId     26721 non-null int64
wr          26721 non-null float64
year        26719 non-null object
title2      26718 non-null object
genres      26721 non-null object
imdbId_y    26721 non-null int64
poster_y    17369 non-null object
title       26721 non-null object
tmdbId_y    26642 non-null float64
dtypes: float64(2), int64(2), object(5)
memory usage: 1.8+ MB

KeyError: 0

In [56]:
def movieToPoster(movieDf,recommenderOutput):
    recommenderOutput = pd.DataFrame(recommenderOutput)
    recommenderOutput.reset_index(drop = True, inplace = True)
    full_df=pd.DataFrame()
    for z in range(len(recommenderOutput)):
#         print(z)
        new_df = movieDf.loc[movieDf['title'] == recommenderOutput['title_x'][z]]
#        new_df = movieDf.loc[movieDf['title'] == recommenderOutput['title_x'][z]]
        full_df = full_df.append(new_df)
        full_df.reset_index(drop = True, inplace = True)
        full_df = full_df.sort_values('wr', ascending=False)
#         print(full_df)
    return full_df

In [57]:
movieToPoster(noNA,newoutput)

,movieId,wr,year,title2,genres,imdbId_y,poster_y,title,tmdbId_y
0,3996,3.806892,Wo hu cang long,"crouchingtiger,hiddendragon",Action|Drama|Romance,190332,https://image.tmdb.org/t/p/w500/zooZQuDBqRpIoD...,"Crouching Tiger, Hidden Dragon (Wo hu cang lon...",146.0
1,7099,3.756975,Kaze no tani no Naushika,nausicaäofthevalleyofthewind,Adventure|Animation|Drama|Fantasy|Sci-Fi,87544,https://image.tmdb.org/t/p/w500/hnYowHwLq0iUWr...,Nausicaä of the Valley of the Wind (Kaze no ta...,81.0
2,3703,3.537136,Mad Max 2,"roadwarrior,the",Action|Adventure|Sci-Fi|Thriller,82694,https://image.tmdb.org/t/p/w500/voNuYkvQgDSqij...,"Road Warrior, The (Mad Max 2) (1981)",8810.0
3,2141,3.277870,1986,"americantail,an",Adventure|Animation|Children|Comedy,90633,https://image.tmdb.org/t/p/w500/glZNfxN4cef0pJ...,"American Tail, An (1986)",4978.0
4,8371,3.238134,2004,"chroniclesofriddick,the",Action|Sci-Fi|Thriller,296572,https://image.tmdb.org/t/p/w500/hVAfGskQdktDwY...,"Chronicles of Riddick, The (2004)",2789.0
5,1587,3.163403,1982,conanthebarbarian,Action|Adventure|Fantasy,82198,https://image.tmdb.org/t/p/w500/9siMCK6u0TtgDV...,Conan the Barbarian (1982),9387.0
6,130520,3.120703,2015,Home,Adventure|Animation|Children|Comedy|Fantasy|Sc...,2224026,https://image.tmdb.org/t/p/w500/8WmT9i9sili2uL...,Home (2015),228161.0
7,26340,3.119147,Les douze travaux d'Astérix,"twelvetasksofasterix,the",Action|Adventure|Animation|Children|Comedy|Fan...,72901,https://image.tmdb.org/t/p/w500/7cZQZOYZFJcLjZ...,"Twelve Tasks of Asterix, The (Les douze travau...",9385.0
8,2826,3.111742,1999,"13thwarrior,the",Action|Adventure|Fantasy,120657,https://image.tmdb.org/t/p/w500/ooR8S0O0ZgxK2O...,"13th Warrior, The (1999)",1911.0
9,120474,3.077176,2014,Toy Story That Time Forgot,Animation|Children,3473654,https://image.tmdb.org/t/p/w500/bxLjTD2FutUHjI...,Toy Story That Time Forgot (2014),256835.0
10,131739,3.071044,2015,Batman vs. Robin,Action|Adventure|Animation,4324274,https://image.tmdb.org/t/p/w500/6g7iQJAgyDn9me...,Batman vs. Robin (2015),321528.0
11,5081,3.068811,2001,birthdaygirl,Drama|Romance,188453,https://image.tmdb.org/t/p/w500/34ps7KL4l3yXeo...,Birthday Girl (2001),2084.0
12,131248,3.068403,2006,Brother Bear 2,Adventure|Animation|Children|Comedy|Fantasy,465925,https://image.tmdb.org/t/p/w500/msZSTfilEF6hw4...,Brother Bear 2 (2006),10010.0
13,27528,3.066131,2001,"warrior,the",Adventure|Drama,295682,https://image.tmdb.org/t/p/w500/9GlrmbZO7VGyqh...,"Warrior, The (2001)",23305.0
14,26043,3.066021,1958,"vikings,the",Action|Adventure,52365,https://image.tmdb.org/t/p/w500/tAar5EMLxM5xUC...,"Vikings, The (1958)",42661.0
19,115879,3.063592,2011,Toy Story Toons: Small Fry,Adventure|Animation|Children|Comedy|Fantasy,2033372,https://image.tmdb.org/t/p/w500/4deuIpnrXuzMAg...,Toy Story Toons: Small Fry (2011),82424.0
15,117922,3.062729,2011,Ice Age: A Mammoth Christmas,Adventure|Animation|Children,2100546,https://image.tmdb.org/t/p/w500/bBKkG54YXVTFCK...,Ice Age: A Mammoth Christmas (2011),79218.0
16,115875,3.060721,2011,Toy Story Toons: Hawaiian Vacation,Adventure|Animation|Children|Comedy|Fantasy,1850374,https://image.tmdb.org/t/p/w500/c0K2qAo0UlFMEq...,Toy Story Toons: Hawaiian Vacation (2011),77887.0
17,3757,3.058868,1972,asylum,Horror,68230,https://image.tmdb.org/t/p/w500/8FXESe9NCN20ln...,Asylum (1972),25993.0
18,5183,3.041778,a.k.a. Blood Wedding,heknowsyou'realone,Horror|Thriller,80850,https://image.tmdb.org/t/p/w500/90rdztFCRAxQsE...,He Knows You're Alone (a.k.a. Blood Wedding) (...,65262.0

In [46]:
nemo_rec = pd.DataFrame(nemo_rec)

In [47]:
nemo_rec

                                                 title_x
1667                            American Tail, An (1986)
2753                       Road to El Dorado, The (2000)
2483                    7th Voyage of Sinbad, The (1958)
3261                    Brave Little Toaster, The (1987)
5625                               Beyond Borders (2003)
7318   Twelve Tasks of Asterix, The (Les douze travau...
16108                                    99 Homes (2014)
15983                     The Fox and the Hound 2 (2006)
2160                           Outrageous Fortune (1987)
4021                    Jimmy Neutron: Boy Genius (2001)